'use strict';


let bl = {
    "modelObj": null,
    "model": null,
    "soajs_service": null,
    "list": function (soajs, inputmaskData, localConfig, cb) {
        let l_modelObj = bl.modelObj;
        if (soajs && soajs.tenant && soajs.tenant.type === "client" && soajs.tenant.dbConfig) {
            l_modelObj = new bl.model(bl.soajs_service, soajs.tenant.dbConfig, null);
        }
        l_modelObj.listTenants(null, (err, records) => {
            if (err) {
                soajs.log.error(err);
                if (soajs && soajs.tenant && soajs.tenant.type === "client" && soajs.tenant.dbConfig) {
                    l_modelObj.closeConnection();
                }
                return cb({
                    "code": 436,
                    "msg": localConfig.errors[436]
                });
            }
            if (soajs && soajs.tenant && soajs.tenant.type === "client" && soajs.tenant.dbConfig) {
                l_modelObj.closeConnection();
            }
            return cb(null, records);
        });
    },

    "add": function (soajs, inputmaskData, localConfig, cb) {
        //TODO: Generate code if not input by user by checking the existed codes of all tenants up to a 25 times count request.
        // if exist don't add
        // if not check on the insert if the generated code is also generated by another request so you got no dupliacate
        // the count request limit must not exceed 25 times.
    },
};

module.exports = bl;